### ISSUE TITLE
error ofox 11

### ISSUE THREAD

**Issue by ghost** [cd-Spidey/OrangeFox-Action-Builder#1]
bro i got this issue while build ofox 11

Run haya14busa/action-cond@v1
  with:
    cond: true
    if_true: lunch twrp_viva-eng && mka adbd bootimage
    if_false: lunch twrp_viva-eng && mka bootimage
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/[2](https://github.com/edenefrii77/OrangeFox-Action-Builder/actions/runs/3394627520/jobs/5644157098#step:12:2)022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by cd-Spidey** [comment]
Nevermind that 'set-output' error, only haya14busa can fix that.

**Comment by cd-Spidey** [comment]
Also, if you are building for A11 and 12.1, my orangefox builder does not work in that manifest, like what I said in readme.

**Comment by cd-Spidey** [comment]
Sorry for late reply, but I have to close this.


This issue are already solved, and builder is working fine.
