### ISSUE TITLE
grub-efi-amd64-signed

### ISSUE THREAD

**Issue by plente00** [cd-Spidey/OrangeFox-Action-Builder#3]
Errors were encountered while processing:
 grub-efi-amd64-signed
 php8.1-fpm
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error: Process completed with exit code 100.

**Comment by cd-Spidey** [comment]
> Errors were encountered while processing: grub-efi-amd64-signed php8.1-fpm needrestart is being skipped since dpkg has failed E: Sub-process /usr/bin/dpkg returned an error code (1) Error: Process completed with exit code 100.

I didn't update this Builder, as it doesn't have support for manifest 11 and 12. Are you building 11 or 12?

**Comment by plente00** [comment]
android 11

**Comment by cd-Spidey** [comment]
> android 11

Ah, nah. Dont use it. Use the OrangeFox-CI, its much easier.

**Comment by plente00** [comment]
manifest please

**Comment by cd-Spidey** [comment]
Builder is working now in most of branches including 11 and 12.1, and even older manifest branches.

I will close this now.
